language: java
jdk:
  - oraclejdk8
os: linux

env:

git:
  depth: 1

matrix:
  fast_finish: true
  include:
    - script: mvn checkstyle:check -B
  allow_failures:
    - script: mvn checkstyle:check -B


cache:
  directories:
    $HOME/.m2/

script: mvn package -B

addons:
  apt:
    update: true
